name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build --strict_front_matter --trace
        env:
          JEKYLL_ENV: production
